version: '3.8'

services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - .:/workspaces/qc-standards-app:cached
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qc_standards
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=true
      - SECRET_KEY=devkey-codespaces-2024
      - BACKEND_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,https://*.githubpreview.dev,https://*.github.dev
      - ENVIRONMENT=development
    networks:
      - qc-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qc_standards
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--auth-local=trust --auth-host=md5
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qc_standards"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - qc-network
    # Dodatkowe ustawienia dla Codespaces
    shm_size: 128mb
    command: >
      postgres 
      -c shared_preload_libraries=''
      -c max_connections=100
      -c shared_buffers=64MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=16MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - qc-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  qc-network:
    driver: bridge