version: '3.8'

services:
  backend:
    image: mcr.microsoft.com/devcontainers/python:3
    volumes:
      - .:/workspaces/qc-standards-app:cached
    command: sleep infinity
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qc_standards
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=true
      - SECRET_KEY=devkey
      - BACKEND_CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qc_standards
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: