# Minimal configuration for Codespaces
version: '3.8'

services:
  db:
    image: postgres:15-alpine  # Lighter Alpine version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qc_standards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: >
      postgres
      -c shared_buffers=64MB
      -c max_connections=50
      -c work_mem=2MB
      -c maintenance_work_mem=32MB

  redis:
    image: redis:7-alpine  # Lighter Alpine version
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    command: >
      redis-server
      --maxmemory 32mb
      --maxmemory-policy allkeys-lru

volumes:
  postgres_data:
